import React, { useEffect } from "react";
import { View, Text, ScrollView, StyleSheet, Dimensions } from "react-native";
import { useNavigation } from "@react-navigation/native";
import { ArrowLeftIcon } from "react-native-heroicons/outline"; // Assuming you have heroicons installed

const { width } = Dimensions.get('window');

export default function TermsOfService() {
  const navigation = useNavigation();

  // In React Native, scrolling to top is often handled by ScrollView props or
  // by the navigation library itself when a new screen is pushed.
  // If specific scroll-to-top behavior is needed, it would be implemented
  // using a ref on the ScrollView and its scrollTo method.
  // For now, we'll omit the useEffect for window.scrollTo as it's web-specific.

  return (
    <ScrollView contentContainerStyle={styles.container}>
      <View style={styles.contentCard}>
        {/* Back Button - React Native style */}
        {/* This will be handled by the Layout component's header or a custom header if needed */}
        {/* For now, we'll rely on the navigation stack's back button or the Layout's navigation */}

        <View style={styles.headerSection}>
          <Text style={styles.title}>Terms of Service</Text>
          <Text style={styles.lastUpdated}>Last Updated: November 27, 2025</Text>
        </View>

        <View style={styles.sectionContainer}>
            
          <Section
            title="1. Acceptance of Terms"
            content="By creating an account or accessing FiamBond ('The Service'), you agree to be bound by these Terms. If you do not agree, you may not use the Service. FiamBond is a digital ledger application designed for tracking financial records; it is not a bank, wallet, or financial institution."
          />

          <Section
            title="2. Description of Service"
            content="FiamBond provides a platform for tracking loans, debts, and payroll through three distinct 'Realms':"
          />
          <BulletPoint
            boldText="Personal Realm:"
            content="For individual tracking and smart loans between friends."
          />
          <BulletPoint
            boldText="Family Realm:"
            content="Shared tracking for household expenses and budgets."
          />
          <BulletPoint
            boldText="Company Realm:"
            content="Professional suite for employee cash advances and payroll generation."
          />

          <Section
            title="3. User Responsibilities"
            content="You are solely responsible for the accuracy of the data you input. FiamBond acts as a calculator and storage system for the data you provide ('The Ledger of Truth'). We do not verify the legality or reality of the debts recorded. You agree not to use the platform for money laundering or illegal activities."
          />

          <Section
            title="4. Subscriptions & Payments"
            content="Access to 'Company Realm' features requires a paid subscription (Monthly or Annual)."
          />
          <BulletPoint
            boldText="Billing Cycle:"
            content="Fees are billed in advance on a recurring basis."
          />
          <BulletPoint
            boldText="Cancellations:"
            content="You may cancel at any time. Your access will continue until the end of the current billing period."
          />
          <BulletPoint
            boldText="Refunds:"
            content="Refunds are handled on a case-by-case basis within 7 days of payment."
          />

          <Section
            title="5. Disclaimer of Liability"
            content="FiamBond is provided 'AS IS'. We are not liable for any disputes arising between users regarding debts recorded on the platform. The 'Payslips' generated by the system are for record-keeping purposes and rely entirely on user input."
          />

          <Section
            title="6. Termination"
            content="We reserve the right to suspend or terminate accounts that violate these terms, including but not limited to fraudulent use or harassment of other users via the loan request system."
          />

        </View>
      </View>
    </ScrollView>
  );
}

// Helper component for sections
const Section = ({ title, content }) => (
  <View style={styles.section}>
    <Text style={styles.sectionTitle}>{title}</Text>
    <Text style={styles.sectionContent}>{content}</Text>
  </View>
);

// Helper component for bullet points
const BulletPoint = ({ boldText, content }) => (
  <View style={styles.bulletPoint}>
    <Text style={styles.bulletPointMarker}>•</Text>
    {boldText && <Text style={styles.bulletPointBoldText}>{boldText} </Text>}
    <Text style={styles.bulletPointContent}>{content}</Text>
  </View>
);

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: '#f9fafb', // bg-gray-50
    paddingVertical: 30, // py-12
    paddingHorizontal: 16, // px-4
  },
  contentCard: {
    maxWidth: 800, // max-w-4xl
    width: '100%',
    alignSelf: 'center',
    backgroundColor: '#ffffff', // bg-white
    borderRadius: 24, // rounded-3xl
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 15,
    elevation: 5, // shadow-xl
    padding: 32, // p-8 md:p-12
    borderColor: '#e5e7eb', // border border-gray-100
  },
  headerSection: {
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb', // border-b border-gray-100
    paddingBottom: 30, // pb-8
    marginBottom: 30, // mb-8
  },
  title: {
    fontSize: 30, // text-3xl md:text-4xl
    fontWeight: '800', // font-extrabold
    color: '#111827', // text-gray-900
    marginBottom: 8, // mb-2
  },
  lastUpdated: {
    color: '#6b7280', // text-gray-500
    fontSize: 12, // text-sm
    fontWeight: '500', // font-medium
    textTransform: 'uppercase', // uppercase
    letterSpacing: 1.5, // tracking-wider
  },
  sectionContainer: {
    // space-y-8
  },
  section: {
    marginBottom: 32, // space-y-8 equivalent for sections
  },
  sectionTitle: {
    fontSize: 20, // text-xl
    fontWeight: '700', // font-bold
    color: '#111827', // text-gray-900
    marginBottom: 12, // mb-3
  },
  sectionContent: {
    color: '#4b5563', // text-gray-600
    lineHeight: 24, // leading-relaxed
    marginBottom: 12,
  },
  bulletPoint: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
    paddingLeft: 10, // Indent for bullet points
  },
  bulletPointMarker: {
    marginRight: 5,
    color: '#4b5563',
  },
  bulletPointBoldText: {
    fontWeight: 'bold',
    color: '#4b5563',
  },
  bulletPointContent: {
    flex: 1,
    color: '#4b5563',
    lineHeight: 24,
  },
});
