import { useEffect } from "react";
import { Link } from "react-router-dom";
import { Helmet } from "react-helmet-async";

export default function TermsOfService() {
  // Ensure page starts at the top when loaded
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8 font-sans text-gray-900">
      <Helmet>
        <title>Terms of Service | FiamBond</title>
      </Helmet>

      <div className="max-w-4xl mx-auto">
        {/* Back Button */}
        <div className="mb-8">
            <Link to="/welcome" className="inline-flex items-center text-indigo-600 hover:text-indigo-800 font-semibold transition-colors">
                <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path></svg>
                Back to Home
            </Link>
        </div>

        {/* Main Content Card */}
        <div className="bg-white rounded-3xl shadow-xl p-8 md:p-12 border border-gray-100">
          <div className="border-b border-gray-100 pb-8 mb-8">
            <h1 className="text-3xl md:text-4xl font-extrabold text-gray-900 mb-2">Terms of Service</h1>
            <p className="text-gray-500 text-sm font-medium uppercase tracking-wider">Last Updated: November 27, 2025</p>
          </div>

          <div className="space-y-8 text-gray-600 leading-relaxed">
            
            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-3">1. Acceptance of Terms</h2>
              <p>
                By creating an account or accessing FiamBond ("The Service"), you agree to be bound by these Terms. 
                If you do not agree, you may not use the Service. FiamBond is a digital ledger application designed 
                for tracking financial records; it is <strong>not</strong> a bank, wallet, or financial institution.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-3">2. Description of Service</h2>
              <p className="mb-3">
                FiamBond provides a platform for tracking loans, debts, and payroll through three distinct "Realms":
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Personal Realm:</strong> For individual tracking and smart loans between friends.</li>
                <li><strong>Family Realm:</strong> Shared tracking for household expenses and budgets.</li>
                <li><strong>Company Realm:</strong> Professional suite for employee cash advances and payroll generation.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-3">3. User Responsibilities</h2>
              <p>
                You are solely responsible for the accuracy of the data you input. FiamBond acts as a calculator and storage 
                system for the data you provide ("The Ledger of Truth"). We do not verify the legality or reality of 
                the debts recorded. You agree not to use the platform for money laundering or illegal activities.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-3">4. Subscriptions & Payments</h2>
              <p className="mb-3">
                Access to "Company Realm" features requires a paid subscription (Monthly or Annual).
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Billing Cycle:</strong> Fees are billed in advance on a recurring basis.</li>
                <li><strong>Cancellations:</strong> You may cancel at any time. Your access will continue until the end of the current billing period.</li>
                <li><strong>Refunds:</strong> Refunds are handled on a case-by-case basis within 7 days of payment.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-3">5. Disclaimer of Liability</h2>
              <p>
                FiamBond is provided "AS IS". We are not liable for any disputes arising between users regarding 
                debts recorded on the platform. The "Payslips" generated by the system are for record-keeping purposes 
                and rely entirely on user input.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-3">6. Termination</h2>
              <p>
                We reserve the right to suspend or terminate accounts that violate these terms, including but not limited 
                to fraudulent use or harassment of other users via the loan request system.
              </p>
            </section>

          </div>
        </div>
      </div>
    </div>
  );
}