import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // ⭐️ CRITICAL FIX: Enables static HTML export mode.
  // The 'out' directory will be generated by 'next build'.
  output: 'export', 

  // optional: If you had any previous configurations, they would go here.
  // For example, if you wanted to change the output folder name:
  // distDir: 'build', 
  
  // NOTE: Static export is incompatible with Server Components/API Routes that require a server.
  // We assume your migration made all necessary components client-side compatible 
  // or that your API is hosted elsewhere.
};

export default nextConfig;